export const FETCH_PRODUCTSLIST_REQUEST = 'FETCH_PRODUCTSLIST_REQUEST';
export const FETCH_PRODUCTSLIST_SUCCESS = 'FETCH_PRODUCTSLIST_SUCCESS';
export const FETCH_PRODUCTSLIST_ERROR = 'FETCH_PRODUCTSLIST_ERROR';

export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR';
