export const FETCH_PRODUCTSLIST_REQUEST = 'FETCH_PRODUCTSLIST_REQUEST';
export const FETCH_PRODUCTSLIST_SUCCESS = 'FETCH_PRODUCTSLIST_SUCCESS';
export const FETCH_PRODUCTSLIST_ERROR = 'FETCH_PRODUCTSLIST_ERROR';

export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const UPDATE_CART_QTY = 'UPDATE_CART_QTY';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
